# Generated by Django 4.1.7 on 2023-05-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to='groups/'),
        ),
    ]
