# Generated by Django 4.1.7 on 2023-07-12 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='active_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
