# Generated by Django 4.1.7 on 2023-03-30 17:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default-avatar.png', upload_to=users.models.user_avatar_path),
        ),
    ]
